all:
	arm-linux-gcc -static -o watchdog-test watchdog-test.c
	arm-linux-gcc -static -o watchdog-simple-cannotstop watchdog-simple-cannotstop.c
	arm-linux-gcc -static -o watchdog-simple-canstop watchdog-simple-canstop.c